## ML-Zoomcamp 2023 

### First Homework

#### Question 1:
What's the version of Pandas that you installed? For this homework, we'll use the California Housing Prices dataset. 

In [22]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from numpy.linalg import inv

In [23]:
pd.__version__

'2.0.3'

In [24]:
df = pd.read_csv("C:/Users/agundogdu/Desktop/kişisel/Untitled Folder/HW1/housing.csv")

In [25]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

#### Question 2:
How many columns are in the dataset?

In [26]:
df.shape

(20640, 10)

#### Question 3:
Which columns in the dataset have missing values?

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


#### Question 4:
How many unique values does the ocean_proximity column have?

In [28]:
df["ocean_proximity"].unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

#### Question 5:
What's the average value of the median_house_value for the houses located near the bay?

In [29]:
df.groupby("ocean_proximity").agg({"median_house_value": "mean"})

median_house_value
ocean_proximity                    
<1H OCEAN             240084.285464
INLAND                124805.392001
ISLAND                380440.000000
NEAR BAY              259212.311790
NEAR OCEAN            249433.977427

#### Question 6:
* Calculate the average of total_bedrooms column in the dataset.
* Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
* Now, calculate the average of total_bedrooms again.
Has it changed?

In [30]:
ave = df["total_bedrooms"].mean();ave

537.8705525375618

In [31]:
df["total_bedrooms"].fillna(ave)

0         129.0
1        1106.0
2         190.0
3         235.0
4         280.0
          ...  
20635     374.0
20636     150.0
20637     485.0
20638     409.0
20639     616.0
Name: total_bedrooms, Length: 20640, dtype: float64

In [32]:
df["total_bedrooms"].fillna(ave).mean()

537.8705525375617

#### Question 7:
* Select all the options located on islands.
* Select only columns housing_median_age, total_rooms, total_bedrooms.
* Get the underlying NumPy array. Let's call it X.
* Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
* Compute the inverse of XTX.
* Create an array y with values [950, 1300, 800, 1000, 1300].
* Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
* What's the value of the last element of w?

In [33]:
select_location = df.loc[df["ocean_proximity"] == "ISLAND"]

In [34]:
x = np.array(select_location[["housing_median_age", "total_rooms", "total_bedrooms"]])

In [56]:
mmm = np.dot(x.T, x); mmm

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [57]:
inverse = inv(mmm); inverse

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [58]:
 y = np.array([950, 1300, 800, 1000, 1300]);y

array([ 950, 1300,  800, 1000, 1300])

In [59]:
multipleXTX = np.dot(inverse, x.T)

In [60]:
w = np.dot(multipleXTX, y); w

array([23.12330961, -1.48124183,  5.69922946])